name: Deploy to Firebase Hosting on push
on:
  workflow_dispatch:
  push:
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - run: bun install && bun run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PORTFOLIO_RAJAN_PHADNIS }}
          projectId: portfolio-rajan-phadnis
          target: pdf
          channelId: live
